"""Built-in Bring! article catalog extracted from the Bring web app."""
from typing import Final

# category, article name, exact Bring CDN image id
CATALOG_ITEMS: Final[tuple[tuple[str, str, str], ...]] = (
    ('Früchte & Gemüse', 'Ananas', 'ananas'),
    ('Früchte & Gemüse', 'Äpfel', 'aepfel'),
    ('Früchte & Gemüse', 'Aprikosen', 'aprikosen'),
    ('Früchte & Gemüse', 'Artischocken', 'artischocken'),
    ('Früchte & Gemüse', 'Aubergine', 'aubergine'),
    ('Früchte & Gemüse', 'Avocado', 'avocado'),
    ('Früchte & Gemüse', 'Bananen', 'bananen'),
    ('Früchte & Gemüse', 'Basilikum', 'basilikum'),
    ('Früchte & Gemüse', 'Beeren', 'beeren'),
    ('Früchte & Gemüse', 'Birnen', 'birnen'),
    ('Früchte & Gemüse', 'Blumenkohl', 'blumenkohl'),
    ('Früchte & Gemüse', 'Brokkoli', 'brokkoli'),
    ('Früchte & Gemüse', 'Brombeeren', 'brombeeren'),
    ('Früchte & Gemüse', 'Champignons', 'champignons'),
    ('Früchte & Gemüse', 'Cherrytomaten', 'cherrytomaten'),
    ('Früchte & Gemüse', 'Datteln', 'datteln'),
    ('Früchte & Gemüse', 'Erbsen', 'erbsen'),
    ('Früchte & Gemüse', 'Erdbeeren', 'erdbeeren'),
    ('Früchte & Gemüse', 'Feigen', 'feigen'),
    ('Früchte & Gemüse', 'Fenchel', 'fenchel'),
    ('Früchte & Gemüse', 'Früchte', 'fruechte'),
    ('Früchte & Gemüse', 'Frühlingszwiebeln', 'fruehlingszwiebeln'),
    ('Früchte & Gemüse', 'Gemüse', 'gemuese'),
    ('Früchte & Gemüse', 'Getrocknete Tomaten', 'getrocknete_tomaten'),
    ('Früchte & Gemüse', 'Grapefruit', 'grapefruit'),
    ('Früchte & Gemüse', 'Gurke', 'gurke'),
    ('Früchte & Gemüse', 'Heidelbeeren', 'heidelbeeren'),
    ('Früchte & Gemüse', 'Himbeeren', 'himbeeren'),
    ('Früchte & Gemüse', 'Ingwer', 'ingwer'),
    ('Früchte & Gemüse', 'Kaki', 'kaki'),
    ('Früchte & Gemüse', 'Karotten', 'karotten'),
    ('Früchte & Gemüse', 'Kartoffeln', 'kartoffeln'),
    ('Früchte & Gemüse', 'Kirschen', 'kirschen'),
    ('Früchte & Gemüse', 'Kiwi', 'kiwi'),
    ('Früchte & Gemüse', 'Knoblauch', 'knoblauch'),
    ('Früchte & Gemüse', 'Kohl', 'kohl'),
    ('Früchte & Gemüse', 'Kohlrabi', 'kohlrabi'),
    ('Früchte & Gemüse', 'Koriander', 'koriander'),
    ('Früchte & Gemüse', 'Kräuter', 'kraeuter'),
    ('Früchte & Gemüse', 'Kürbis', 'kuerbis'),
    ('Früchte & Gemüse', 'Lattich', 'lattich'),
    ('Früchte & Gemüse', 'Lauch', 'lauch'),
    ('Früchte & Gemüse', 'Limette', 'limette'),
    ('Früchte & Gemüse', 'Mais', 'mais'),
    ('Früchte & Gemüse', 'Mandarinen', 'mandarinen'),
    ('Früchte & Gemüse', 'Mango', 'mango'),
    ('Früchte & Gemüse', 'Melone', 'melone'),
    ('Früchte & Gemüse', 'Nektarine', 'nektarine'),
    ('Früchte & Gemüse', 'Oliven', 'oliven'),
    ('Früchte & Gemüse', 'Orange', 'orange'),
    ('Früchte & Gemüse', 'Passionsfrucht', 'passionsfrucht'),
    ('Früchte & Gemüse', 'Peperoncini', 'peperoncini'),
    ('Früchte & Gemüse', 'Peperoni', 'peperoni'),
    ('Früchte & Gemüse', 'Petersilie', 'petersilie'),
    ('Früchte & Gemüse', 'Pfefferminze', 'pfefferminze'),
    ('Früchte & Gemüse', 'Pfirsich', 'pfirsich'),
    ('Früchte & Gemüse', 'Pflaumen', 'pflaumen'),
    ('Früchte & Gemüse', 'Pilze', 'pilze'),
    ('Früchte & Gemüse', 'Radieschen', 'radieschen'),
    ('Früchte & Gemüse', 'Randen', 'rote_bete'),
    ('Früchte & Gemüse', 'Rhabarber', 'rhabarber'),
    ('Früchte & Gemüse', 'Rucola', 'rucola'),
    ('Früchte & Gemüse', 'Salat', 'salat'),
    ('Früchte & Gemüse', 'Salbei', 'salbei'),
    ('Früchte & Gemüse', 'Schnittlauch', 'schnittlauch'),
    ('Früchte & Gemüse', 'Sellerie', 'sellerie'),
    ('Früchte & Gemüse', 'Spargel', 'spargel'),
    ('Früchte & Gemüse', 'Spinat', 'spinat'),
    ('Früchte & Gemüse', 'Süsskartoffeln', 'suesskartoffeln'),
    ('Früchte & Gemüse', 'Thymian', 'thymian'),
    ('Früchte & Gemüse', 'Tomaten', 'tomaten'),
    ('Früchte & Gemüse', 'Trauben', 'trauben'),
    ('Früchte & Gemüse', 'Wassermelone', 'wassermelone'),
    ('Früchte & Gemüse', 'Zitrone', 'zitrone'),
    ('Früchte & Gemüse', 'Zucchetti', 'zucchetti'),
    ('Früchte & Gemüse', 'Zwetschgen', 'zwetschgen'),
    ('Früchte & Gemüse', 'Zwiebeln', 'zwiebeln'),
    ('Brot & Gebäck', 'Baguette', 'baguette'),
    ('Brot & Gebäck', 'Blätterteig', 'blaetterteig'),
    ('Brot & Gebäck', 'Brot', 'brot'),
    ('Brot & Gebäck', 'Brötchen', 'broetchen'),
    ('Brot & Gebäck', 'Gipfeli', 'gipfeli'),
    ('Brot & Gebäck', 'Knäckebrot', 'knaeckebrot'),
    ('Brot & Gebäck', 'Muffins', 'muffins'),
    ('Brot & Gebäck', 'Pizzateig', 'pizzateig'),
    ('Brot & Gebäck', 'Toast', 'toast'),
    ('Brot & Gebäck', 'Waffeln', 'waffeln'),
    ('Brot & Gebäck', 'Zopf', 'zopf'),
    ('Milch & Käse', 'Blauschimmelkäse', 'blauschimmelkaese'),
    ('Milch & Käse', 'Burrata', 'burrata'),
    ('Milch & Käse', 'Butter', 'butter'),
    ('Milch & Käse', 'Creme fraiche', 'creme_fraiche'),
    ('Milch & Käse', 'Eier', 'eier'),
    ('Milch & Käse', 'Feta', 'feta'),
    ('Milch & Käse', 'Fondue', 'fondue'),
    ('Milch & Käse', 'Frischkäse', 'frischkaese'),
    ('Milch & Käse', 'Gorgonzola', 'gorgonzola'),
    ('Milch & Käse', 'Hüttenkäse', 'huettenkaese'),
    ('Milch & Käse', 'Joghurt', 'joghurt'),
    ('Milch & Käse', 'Käse', 'kaese'),
    ('Milch & Käse', 'Kräuterbutter', 'kraeuterbutter'),
    ('Milch & Käse', 'Margarine', 'margarine'),
    ('Milch & Käse', 'Mascarpone', 'mascarpone'),
    ('Milch & Käse', 'Milch', 'milch'),
    ('Milch & Käse', 'Mozzarella', 'mozzarella'),
    ('Milch & Käse', 'Parmesan', 'parmesan'),
    ('Milch & Käse', 'Quark', 'quark'),
    ('Milch & Käse', 'Raclette', 'raclette'),
    ('Milch & Käse', 'Rahm', 'rahm'),
    ('Milch & Käse', 'Reibkäse', 'reibkaese'),
    ('Milch & Käse', 'Ricotta', 'ricotta'),
    ('Milch & Käse', 'Sauerrahm', 'sauerrahm'),
    ('Milch & Käse', 'Sojamilch', 'soya_milch'),
    ('Fleisch & Fisch', 'Aufschnitt', 'aufschnitt'),
    ('Fleisch & Fisch', 'Bratwurst', 'bratwurst'),
    ('Fleisch & Fisch', 'Bresaola', 'bresaola'),
    ('Fleisch & Fisch', 'Bündnerfleisch', 'b'),
    ('Fleisch & Fisch', 'Cervelat', 'cervelat'),
    ('Fleisch & Fisch', 'Cordon Bleu', 'c'),
    ('Fleisch & Fisch', 'Fisch', 'fisch'),
    ('Fleisch & Fisch', 'Fleisch', 'fleisch'),
    ('Fleisch & Fisch', 'Garnelen', 'garnelen'),
    ('Fleisch & Fisch', 'Hackfleisch', 'hackfleisch'),
    ('Fleisch & Fisch', 'Kalbfleisch', 'kalbfleisch'),
    ('Fleisch & Fisch', 'Lachs', 'lachs'),
    ('Fleisch & Fisch', 'Lamm', 'lamm'),
    ('Fleisch & Fisch', 'Muscheln', 'muscheln'),
    ('Fleisch & Fisch', 'Poulet', 'poulet'),
    ('Fleisch & Fisch', 'Pouletbrüstli', 'pouletbruestli'),
    ('Fleisch & Fisch', 'Rindfleisch', 'rindfleisch'),
    ('Fleisch & Fisch', 'Rindsgeschnetzeltes', 'rindsgeschnetzeltes'),
    ('Fleisch & Fisch', 'Rohschinken', 'rohschinken'),
    ('Fleisch & Fisch', 'Salami', 'salami'),
    ('Fleisch & Fisch', 'Sardellen', 'sardellen'),
    ('Fleisch & Fisch', 'Schinken', 'schinken'),
    ('Fleisch & Fisch', 'Schnitzel', 'schnitzel'),
    ('Fleisch & Fisch', 'Schweinefleisch', 'schweinefleisch'),
    ('Fleisch & Fisch', 'Speck', 'speck'),
    ('Fleisch & Fisch', 'Steak', 'steak'),
    ('Fleisch & Fisch', 'Thon', 'thon'),
    ('Fleisch & Fisch', 'Thunfisch', 'thunfisch'),
    ('Fleisch & Fisch', 'Wienerli', 'frankfurter'),
    ('Fleisch & Fisch', 'Wurst', 'wurst'),
    ('Zutaten & Gewürze', 'Ahornsirup', 'ahornsirup'),
    ('Zutaten & Gewürze', 'Apfelmus', 'apfelmus'),
    ('Zutaten & Gewürze', 'Aromat', 'aromat'),
    ('Zutaten & Gewürze', 'Backpulver', 'backpulver'),
    ('Zutaten & Gewürze', 'Balsamico', 'balsamico'),
    ('Zutaten & Gewürze', 'Baumnüsse', 'baumnuesse'),
    ('Zutaten & Gewürze', 'BBQ Sauce', 'bbq_sauce'),
    ('Zutaten & Gewürze', 'Bohnen', 'bohnen'),
    ('Zutaten & Gewürze', 'Bouillon', 'bouillon'),
    ('Zutaten & Gewürze', 'Bratensauce', 'bratensauce'),
    ('Zutaten & Gewürze', 'Dip', 'dip'),
    ('Zutaten & Gewürze', 'Essig', 'essig'),
    ('Zutaten & Gewürze', 'Essiggurken', 'essiggurken'),
    ('Zutaten & Gewürze', 'Haselnüsse', 'haselnuesse'),
    ('Zutaten & Gewürze', 'Hefe', 'hefe'),
    ('Zutaten & Gewürze', 'Kartoffelstock', 'kartoffelstock'),
    ('Zutaten & Gewürze', 'Ketchup', 'ketchup'),
    ('Zutaten & Gewürze', 'Kokosmilch', 'kokosmilch'),
    ('Zutaten & Gewürze', 'Linsen', 'linsen'),
    ('Zutaten & Gewürze', 'Mandelmus', 'mandelmus'),
    ('Zutaten & Gewürze', 'Mandeln', 'mandeln'),
    ('Zutaten & Gewürze', 'Mayonnaise', 'mayonnaise'),
    ('Zutaten & Gewürze', 'Nüsse', 'nuesse'),
    ('Zutaten & Gewürze', 'Öl', 'oel'),
    ('Zutaten & Gewürze', 'Olivenöl', 'olivenoel'),
    ('Zutaten & Gewürze', 'Oregano', 'oregano'),
    ('Zutaten & Gewürze', 'Paniermehl', 'paniermehl'),
    ('Zutaten & Gewürze', 'Paprikapulver', 'paprikapulver'),
    ('Zutaten & Gewürze', 'Pasta Sauce', 'pasta_sauce'),
    ('Zutaten & Gewürze', 'Pelati', 'pelati'),
    ('Zutaten & Gewürze', 'Pfeffer', 'pfeffer'),
    ('Zutaten & Gewürze', 'Pfefferkörner', 'pfefferkoerner'),
    ('Zutaten & Gewürze', 'Pinienkerne', 'pinienkerne'),
    ('Zutaten & Gewürze', 'Preiselbeer Sauce', 'preiselbeer_sauce'),
    ('Zutaten & Gewürze', 'Puderzucker', 'puderzucker'),
    ('Zutaten & Gewürze', 'Rosmarin', 'rosmarin'),
    ('Zutaten & Gewürze', 'Salatsauce', 'salatsauce'),
    ('Zutaten & Gewürze', 'Salz', 'salz'),
    ('Zutaten & Gewürze', 'Sauerkraut', 'sauerkraut'),
    ('Zutaten & Gewürze', 'Senf', 'senf'),
    ('Zutaten & Gewürze', 'Silberzwiebeln', 'silberzwiebeln'),
    ('Zutaten & Gewürze', 'Sojasauce', 'soyasauce'),
    ('Zutaten & Gewürze', 'Speisestärke', 'speisestaerke'),
    ('Zutaten & Gewürze', 'Tomatenmark', 'tomatenmark'),
    ('Zutaten & Gewürze', 'Tomatensauce', 'tomatensauce'),
    ('Zutaten & Gewürze', 'Vanillezucker', 'vanillezucker'),
    ('Zutaten & Gewürze', 'Zimt', 'zimt'),
    ('Zutaten & Gewürze', 'Zucker', 'zucker'),
    ('Fertig- & Tiefkühlprodukte', 'Chicken Wings', 'chicken_wings'),
    ('Fertig- & Tiefkühlprodukte', 'Chinesisches Essen', 'chinese_to_go'),
    ('Fertig- & Tiefkühlprodukte', 'Fischstäbli', 'fischstaebli'),
    ('Fertig- & Tiefkühlprodukte', 'Gemüse gefroren', 'gemuese_gefroren'),
    ('Fertig- & Tiefkühlprodukte', 'Glacé', 'glace'),
    ('Fertig- & Tiefkühlprodukte', 'Indisches Essen', 'indian_to_go'),
    ('Fertig- & Tiefkühlprodukte', 'Italienisches Essen', 'italian_to_go'),
    ('Fertig- & Tiefkühlprodukte', 'Lasagne', 'lasagne'),
    ('Fertig- & Tiefkühlprodukte', 'Pizza', 'pizza'),
    ('Fertig- & Tiefkühlprodukte', 'Pommes Frites', 'pommes_frites'),
    ('Fertig- & Tiefkühlprodukte', 'Suppe', 'suppe'),
    ('Fertig- & Tiefkühlprodukte', 'Thai Essen', 'thai_to_go'),
    ('Getreideprodukte', 'Basmatireis', 'basmatireis'),
    ('Getreideprodukte', 'Corn Flakes', 'corn_flakes'),
    ('Getreideprodukte', 'Couscous', 'couscous'),
    ('Getreideprodukte', 'Gnocchi', 'gnocchi'),
    ('Getreideprodukte', 'Griess', 'griess'),
    ('Getreideprodukte', 'Haferflocken', 'haferflocken'),
    ('Getreideprodukte', 'Kichererbsen', 'kichererbsen'),
    ('Getreideprodukte', 'Mehl', 'mehl'),
    ('Getreideprodukte', 'Müesli', 'mueesli'),
    ('Getreideprodukte', 'Nudeln', 'nudeln'),
    ('Getreideprodukte', 'Orecchiette', 'orecchiette'),
    ('Getreideprodukte', 'Pasta', 'pasta'),
    ('Getreideprodukte', 'Penne', 'penne'),
    ('Getreideprodukte', 'Reis', 'reis'),
    ('Getreideprodukte', 'Risottoreis', 'risottoreis'),
    ('Getreideprodukte', 'Rösti', 'r'),
    ('Getreideprodukte', 'Spaghetti', 'spaghetti'),
    ('Getreideprodukte', 'Tofu', 'tofu'),
    ('Snacks & Süsswaren', 'Brezeln', 'brezeln'),
    ('Snacks & Süsswaren', 'Bring!', 'bring'),
    ('Snacks & Süsswaren', 'Dessert', 'dessert'),
    ('Snacks & Süsswaren', 'Dörrobst', 'doerrobst'),
    ('Snacks & Süsswaren', 'Erdnüsse', 'erdnuesse'),
    ('Snacks & Süsswaren', 'Gelee', 'gelee'),
    ('Snacks & Süsswaren', 'Getreideriegel', 'getreideriegel'),
    ('Snacks & Süsswaren', 'Grissini', 'grissini'),
    ('Snacks & Süsswaren', 'Guetzli', 'guetzli'),
    ('Snacks & Süsswaren', 'Honig', 'honig'),
    ('Snacks & Süsswaren', 'Kaugummi', 'kaugummi'),
    ('Snacks & Süsswaren', 'Kekse', 'kekse'),
    ('Snacks & Süsswaren', 'Konfitüre', 'konfituere'),
    ('Snacks & Süsswaren', 'Kuchen', 'kuchen'),
    ('Snacks & Süsswaren', 'Lebkuchen', 'lebkuchen'),
    ('Snacks & Süsswaren', 'Nougatcreme', 'nougatcreme'),
    ('Snacks & Süsswaren', 'Pommes Chips', 'pommes_chips'),
    ('Snacks & Süsswaren', 'Pop Corn', 'pop_corn'),
    ('Snacks & Süsswaren', 'Schokolade', 'schokolade'),
    ('Snacks & Süsswaren', 'Snacks', 'snacks'),
    ('Snacks & Süsswaren', 'Süssigkeiten', 'suessigkeiten'),
    ('Snacks & Süsswaren', 'Torte', 'torte'),
    ('Snacks & Süsswaren', 'Tortilla Chips', 'tortilla_chips'),
    ('Snacks & Süsswaren', 'Vanille Sauce', 'vanille_sauce'),
    ('Snacks & Süsswaren', 'Vielen Dank', 'vielen_dank'),
    ('Getränke', 'Apfelsaft', 'apfelsaft'),
    ('Getränke', 'Bier', 'bier'),
    ('Getränke', 'Champagner', 'champagner'),
    ('Getränke', 'Cidre', 'cidre'),
    ('Getränke', 'Cola', 'cola'),
    ('Getränke', 'Cola Light', 'cola_light'),
    ('Getränke', 'Eistee', 'eistee'),
    ('Getränke', 'Energy Drink', 'energy_drink'),
    ('Getränke', 'Fruchtsaft', 'fruchtsaft'),
    ('Getränke', 'Getränke', 'getraenke'),
    ('Getränke', 'Gin', 'gin'),
    ('Getränke', 'Kaffee', 'kaffee'),
    ('Getränke', 'Kaffeebohnen', 'k'),
    ('Getränke', 'Kaffeekapseln', 'k'),
    ('Getränke', 'Kaffeepads', 'k'),
    ('Getränke', 'Kakao', 'kakao'),
    ('Getränke', 'Light Limonade', 'light_limonade'),
    ('Getränke', 'Limonade', 'limonade'),
    ('Getränke', 'Mineralwasser', 'mineralwasser'),
    ('Getränke', 'Orangensaft', 'orangensaft'),
    ('Getränke', 'Prosecco', 'prosecco'),
    ('Getränke', 'Rotwein', 'rotwein'),
    ('Getränke', 'Rum', 'rum'),
    ('Getränke', 'Schnaps', 'schnaps'),
    ('Getränke', 'Sirup', 'sirup'),
    ('Getränke', 'Smoothie', 'smoothie'),
    ('Getränke', 'Sportgetränk', 'sportgetraenk'),
    ('Getränke', 'Tee', 'tee'),
    ('Getränke', 'Tonic Water', 'tonic_water'),
    ('Getränke', 'Vodka', 'vodka'),
    ('Getränke', 'Wasser', 'wasser'),
    ('Getränke', 'Weisswein', 'weisswein'),
    ('Getränke', 'Whisky', 'whisky'),
    ('Getränke', 'Zigaretten', 'zigaretten'),
    ('Getränke', 'Zigarren', 'zigarren'),
    ('Getränke', 'Zitronensaft', 'z'),
    ('Haushalt', 'Abfallsäcke', 'abfallsaecke'),
    ('Haushalt', 'Abwaschmittel', 'abwaschmittel'),
    ('Haushalt', 'Alufolie', 'alufolie'),
    ('Haushalt', 'Babynahrung', 'babynahrung'),
    ('Haushalt', 'Backpapier', 'backpapier'),
    ('Haushalt', 'Badreiniger', 'badreiniger'),
    ('Haushalt', 'Batterien', 'batterien'),
    ('Haushalt', 'Blumen', 'blumen'),
    ('Haushalt', 'Frischhaltefolie', 'frischhaltefolie'),
    ('Haushalt', 'Geschenk', 'geschenk'),
    ('Haushalt', 'Geschenkpapier', 'geschenkpapier'),
    ('Haushalt', 'Geschirrglanz', 'geschirrglanz'),
    ('Haushalt', 'Geschirrsalz', 'geschirrsalz'),
    ('Haushalt', 'Geschirrtabs', 'geschirrtabs'),
    ('Haushalt', 'Glasreiniger', 'glasreiniger'),
    ('Haushalt', 'Glühbirne', 'gluehbirne'),
    ('Haushalt', 'Haushaltspapier', 'haushaltspapier'),
    ('Haushalt', 'Kerzen', 'kerzen'),
    ('Haushalt', 'Putzmittel', 'putzmittel'),
    ('Haushalt', 'Schwamm', 'schwamm'),
    ('Haushalt', 'Servietten', 'servietten'),
    ('Haushalt', 'Spülmittel', 'spuelmittel'),
    ('Haushalt', 'Streichhölzer', 'streichhoelzer'),
    ('Haushalt', 'Strohhalme', 'strohhalme'),
    ('Haushalt', 'Waschmittel', 'waschmittel'),
    ('Haushalt', 'WC-Reiniger', 'wc_reiniger'),
    ('Haushalt', 'Weichspüler', 'weichspueler'),
    ('Haushalt', 'Zahnstocher', 'zahnstocher'),
    ('Tierbedarf', 'Fischfutter', 'fischfutter'),
    ('Tierbedarf', 'Hundefutter', 'hundefutter'),
    ('Tierbedarf', 'Hundesnack', 'hundesnack'),
    ('Tierbedarf', 'Katzenfutter', 'katzenfutter'),
    ('Tierbedarf', 'Katzensnack', 'katzensnack'),
    ('Tierbedarf', 'Katzenstreu', 'katzenstreu'),
    ('Tierbedarf', 'Vogelfutter', 'vogelfutter'),
    ('Baumarkt & Garten', 'Blumenerde', 'blumenerde'),
    ('Baumarkt & Garten', 'Dünger', 'duenger'),
    ('Baumarkt & Garten', 'Gartenwerkzeug', 'gartenwerkzeug'),
    ('Baumarkt & Garten', 'Giesskanne', 'giesskanne'),
    ('Baumarkt & Garten', 'Grill', 'grill'),
    ('Baumarkt & Garten', 'Holzkohle', 'holzkohle'),
    ('Baumarkt & Garten', 'Nägel', 'naegel'),
    ('Baumarkt & Garten', 'Pflanzen', 'pflanzen'),
    ('Baumarkt & Garten', 'Pinsel', 'pinsel'),
    ('Baumarkt & Garten', 'Propangas', 'propangas'),
    ('Baumarkt & Garten', 'Rasenmäher', 'rasenmaeher'),
    ('Baumarkt & Garten', 'Samen', 'samen'),
    ('Baumarkt & Garten', 'Schrauben', 'schrauben'),
    ('Baumarkt & Garten', 'Sonnenschirm', 'sonnenschirm'),
    ('Baumarkt & Garten', 'Töpfe', 'toepfe'),
    ('Pflege & Gesundheit', 'Binden', 'binden'),
    ('Pflege & Gesundheit', 'Bodylotion', 'bodylotion'),
    ('Pflege & Gesundheit', 'Conditioner', 'conditioner'),
    ('Pflege & Gesundheit', 'Deo', 'deo'),
    ('Pflege & Gesundheit', 'Duschmittel', 'duschmittel'),
    ('Pflege & Gesundheit', 'Feuchttücher', 'feuchttuecher'),
    ('Pflege & Gesundheit', 'Gesichtscreme', 'gesichtscreme'),
    ('Pflege & Gesundheit', 'Haargel', 'haargel'),
    ('Pflege & Gesundheit', 'Haarspray', 'haarspray'),
    ('Pflege & Gesundheit', 'Handcreme', 'handcreme'),
    ('Pflege & Gesundheit', 'Insektenschutzmittel', 'insektenschutzmittel'),
    ('Pflege & Gesundheit', 'Kondome', 'kondome'),
    ('Pflege & Gesundheit', 'Kosmetiktücher', 'kosmetiktuecher'),
    ('Pflege & Gesundheit', 'Linsenmittel', 'linsenmittel'),
    ('Pflege & Gesundheit', 'Lippenpomade', 'lippenpomade'),
    ('Pflege & Gesundheit', 'Makeup Entferner', 'makeup_entferner'),
    ('Pflege & Gesundheit', 'Mundspülung', 'mundspuelung'),
    ('Pflege & Gesundheit', 'Nagellack', 'nagellack'),
    ('Pflege & Gesundheit', 'Nagellackentferner', 'nagellackentferner'),
    ('Pflege & Gesundheit', 'Pflaster', 'pflaster'),
    ('Pflege & Gesundheit', 'Rasierer', 'rasierer'),
    ('Pflege & Gesundheit', 'Rasierklingen', 'rasierklingen'),
    ('Pflege & Gesundheit', 'Rasierschaum', 'rasierschaum'),
    ('Pflege & Gesundheit', 'Schmerzmittel', 'schmerzmittel'),
    ('Pflege & Gesundheit', 'Seife', 'seife'),
    ('Pflege & Gesundheit', 'Shampoo', 'shampoo'),
    ('Pflege & Gesundheit', 'Sonnencreme', 'sonnencreme'),
    ('Pflege & Gesundheit', 'Tampons', 'tampons'),
    ('Pflege & Gesundheit', 'Taschentücher', 'taschentuecher'),
    ('Pflege & Gesundheit', 'Vitamine', 'vitamine'),
    ('Pflege & Gesundheit', 'Watterondellen', 'watterondellen'),
    ('Pflege & Gesundheit', 'Wattestäbchen', 'wattestaebchen'),
    ('Pflege & Gesundheit', 'WC-Papier', 'wc_papier'),
    ('Pflege & Gesundheit', 'Windeln', 'windeln'),
    ('Pflege & Gesundheit', 'Zahnbürsten', 'zahnbuersten'),
    ('Pflege & Gesundheit', 'Zahnpasta', 'zahnpasta'),
    ('Pflege & Gesundheit', 'Zahnseide', 'zahnseide'),
)
