const en = {
  show_quick_add: 'Show Quick Add',
  show_quick_add_description: 'Display recently purchased items for quick re-adding',
  show_all_items: 'Show All Items',
  show_all_items_description: 'Display all available items grouped by category',
  max_quick_add_items: 'Max Quick Add Items',
  max_quick_add_items_description: 'Maximum items to show in Quick Add section',
  card_size: 'Card Size',
  card_size_description: 'Size of the product item cards',
  small: 'Small',
  medium: 'Medium',
  large: 'Large',
  no_shopping_lists: 'No shopping lists found',
  failed_to_connect: 'Failed to connect to Bring! integration',
  failed_to_load_list: 'Failed to load shopping list',
  added: 'Added {name}',
  failed_to_add: 'Failed to add item',
  done: 'Done: {name}',
  failed_to_complete: 'Failed to complete item',
  remove: 'Remove',
  clear_list: 'Clear list',
  confirm_clear_list: 'Sure?',
  removed: 'Removed: {name}',
  failed_to_remove: 'Failed to remove item',
  updated: 'Updated',
  failed_to_update: 'Failed to update',
  shopping_card: 'Shopping Card',
  select_list: 'Select List',
  list: 'List',
  sort: 'Sort',
  manual_order: 'Manual Order',
  by_category: 'By Category',
  recently_added: 'Recently Added',
  refresh: 'Refresh',
  add_item_placeholder: 'Add item...',
  add: 'Add',
  to_buy: 'To Buy',
  list_empty: 'List is empty!',
  empty_list_hint: 'Add items above or tap below',
  add_note: '+ note',
  quick_add: 'Quick Add',
  other: 'Other',
  all_items: 'All Items',
  edit: 'Edit: {name}',
  specification_placeholder: 'e.g., 2 lbs, organic',
  cancel: 'Cancel',
  save: 'Save',
} as const;

type TranslationKey = keyof typeof en;
type Translations = Record<TranslationKey, string>;

const de: Translations = {
  show_quick_add: 'Schnell hinzufügen anzeigen',
  show_quick_add_description: 'Kürzlich gekaufte Artikel zum schnellen erneuten Hinzufügen anzeigen',
  show_all_items: 'Alle Artikel anzeigen',
  show_all_items_description: 'Alle verfügbaren Artikel nach Kategorie gruppiert anzeigen',
  max_quick_add_items: 'Maximale Anzahl für Schnell hinzufügen',
  max_quick_add_items_description: 'Maximale Anzahl der Artikel im Bereich „Schnell hinzufügen“',
  card_size: 'Kartengröße',
  card_size_description: 'Größe der Produktkarten',
  small: 'Klein',
  medium: 'Mittel',
  large: 'Groß',
  no_shopping_lists: 'Keine Einkaufslisten gefunden',
  failed_to_connect: 'Verbindung zur Bring!-Integration fehlgeschlagen',
  failed_to_load_list: 'Einkaufsliste konnte nicht geladen werden',
  added: '{name} hinzugefügt',
  failed_to_add: 'Artikel konnte nicht hinzugefügt werden',
  done: 'Erledigt: {name}',
  failed_to_complete: 'Artikel konnte nicht abgeschlossen werden',
  remove: 'Entfernen',
  clear_list: 'Liste leeren',
  confirm_clear_list: 'Sicher?',
  removed: '{name} entfernt',
  failed_to_remove: 'Artikel konnte nicht entfernt werden',
  updated: 'Aktualisiert',
  failed_to_update: 'Aktualisierung fehlgeschlagen',
  shopping_card: 'Einkaufskarte',
  select_list: 'Liste auswählen',
  list: 'Liste',
  sort: 'Sortieren',
  manual_order: 'Manuelle Reihenfolge',
  by_category: 'Nach Kategorie',
  recently_added: 'Kürzlich hinzugefügt',
  refresh: 'Aktualisieren',
  add_item_placeholder: 'Artikel hinzufügen …',
  add: 'Hinzufügen',
  to_buy: 'Zu kaufen',
  list_empty: 'Die Liste ist leer!',
  empty_list_hint: 'Füge oben Artikel hinzu oder tippe unten auf einen Artikel',
  add_note: '+ Notiz',
  quick_add: 'Schnell hinzufügen',
  other: 'Sonstiges',
  all_items: 'Alle Artikel',
  edit: 'Bearbeiten: {name}',
  specification_placeholder: 'z. B. 2 kg, Bio',
  cancel: 'Abbrechen',
  save: 'Speichern',
};

const translations: Record<string, Translations> = { en, de };

export function localize(
  language: string | undefined,
  key: TranslationKey,
  replacements: Record<string, string | number> = {}
): string {
  const normalizedLanguage = language?.toLowerCase().split('-')[0] ?? 'en';
  const translation = (translations[normalizedLanguage] ?? en)[key] ?? en[key];

  return translation.replace(/\{(\w+)\}/g, (placeholder, name) =>
    replacements[name] === undefined ? placeholder : String(replacements[name])
  );
}
